title: Twileloop.FileStorage
description: "A lightweight and ready-made implementation of file persistence for storing your app data or files."
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
github:
  zip_url: https://github.com/sangeethnandakumar/Twileloop.FileStorage/releases
  tar_url: https://www.nuget.org/packages/Twileloop.FileStorage
